name: build

on:
  workflow_dispatch:

jobs:
  ecommerce-website:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build contacts and export to Docker
        uses: docker/build-push-action@v2
        with:
          file: docker/Dockerfile_ecommerce
          load: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ecommerce-website:latest

      - uses: lacework/lw-scanner-action@v1.4.0
        name: Scan contacts container image for vulnerabilities using Lacework
        with:
          LW_ACCOUNT_NAME: ${{ secrets.LW_ACCOUNT_NAME }}
          LW_ACCESS_TOKEN: ${{ secrets.LW_ACCESS_TOKEN }}
          IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/ecommerce-website
          IMAGE_TAG: latest
          SAVE_BUILD_REPORT: true
          PRETTY_OUTPUT: true
          RESULTS_IN_GITHUB_SUMMARY: true
          ADDITIONAL_PARAMETERS:
             use_policy: true
             critical-violation-exit-code: 1

      - name: Build and push frontend
        uses: docker/build-push-action@v2
        with:
          file: docker/Dockerfile_ecommerce
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ecommerce-website:latest

  ecommerce-order-service:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build contacts and export to Docker
        uses: docker/build-push-action@v2
        with:
          file: docker/Dockerfile_order-service
          load: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ecommerce-order:latest

      - uses: lacework/lw-scanner-action@v1.4.0
        name: Scan contacts container image for vulnerabilities using Lacework
        with:
          LW_ACCOUNT_NAME: ${{ secrets.LW_ACCOUNT_NAME }}
          LW_ACCESS_TOKEN: ${{ secrets.LW_ACCESS_TOKEN }}
          IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/ecommerce-order
          IMAGE_TAG: latest

      - name: Build and push frontend
        uses: docker/build-push-action@v2
        with:
          file: docker/Dockerfile_order-service
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ecommerce-order:latest

  ecommerce-inventory:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build contacts and export to Docker
        uses: docker/build-push-action@v2
        with:
          file: docker/Dockerfile_datalayer
          load: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ecommerce-inventory:latest

      - uses: lacework/lw-scanner-action@v1.4.0
        name: Scan contacts container image for vulnerabilities using Lacework
        with:
          LW_ACCOUNT_NAME: ${{ secrets.LW_ACCOUNT_NAME }}
          LW_ACCESS_TOKEN: ${{ secrets.LW_ACCESS_TOKEN }}
          IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/ecommerce-inventory
          IMAGE_TAG: latest

      - name: Build and push frontend
        uses: docker/build-push-action@v2
        with:
          file: docker/Dockerfile_datalayer
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ecommerce-inventory:latest

  ecommerce-login:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build contacts and export to Docker
        uses: docker/build-push-action@v2
        with:
          file: docker/Dockerfile_datalayer
          load: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ecommerce-login:latest

      - uses: lacework/lw-scanner-action@v1.4.0
        name: Scan contacts container image for vulnerabilities using Lacework
        with:
          LW_ACCOUNT_NAME: ${{ secrets.LW_ACCOUNT_NAME }}
          LW_ACCESS_TOKEN: ${{ secrets.LW_ACCESS_TOKEN }}
          IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/ecommerce-login
          IMAGE_TAG: latest

      - name: Build and push frontend
        uses: docker/build-push-action@v2
        with:
          file: docker/Dockerfile_datalayer
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ecommerce-login:latest
